client:
  ip-api:
    url: http://ip-api.com/json
  ip-stack:
    url: http://api.ipstack.com
    api-key: bce3c57a13c16cfe79cbf7e467463036
  open-weather-map:
    url: http://api.openweathermap.org/data/2.5
    api-key: f5e21b7939b3e90c67869841245de61d
logging:
  level:
    lv:
      savchuk:
        weatherbyip:
          client:
            ip:
              IpApiClient: DEBUG
            weather:
              OpenWeatherMapClient: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: FULL
spring:
  flyway:
    enabled: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        use_sql_comments: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console