logging:
  level:
    lv:
      savchuk:
        weatherbyip:
          client:
            ip:
              IpApiClient: DEBUG
feign:
  client:
    config:
      default:
        loggerLevel: FULL
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/db;DB_CLOSE_ON_EXIT=FALSE
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console